"""Message

Revision ID: 979491a2cef7
Revises: 
Create Date: 2023-08-11 16:14:51.837086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979491a2cef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.Column('company_phone', sa.String(length=20), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=20), nullable=False),
    sa.Column('sgk_registry_number', sa.String(length=20), nullable=False),
    sa.Column('sgk_employee_count', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('iban_number', sa.String(length=50), nullable=False),
    sa.Column('representative_name', sa.String(length=255), nullable=False),
    sa.Column('representative_tc', sa.String(length=11), nullable=False),
    sa.Column('representative_title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('TCNo', sa.String(length=11), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('birthplace', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('graduation_status', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('dal', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('TCNo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('person')
    op.drop_table('company_info')
    # ### end Alembic commands ###
